"""FastAPI HTTP API interface for the assistant.

Exposes:
    POST /api/chat                — send a message, get assistant reply
    GET  /api/session/{session_id} — get conversation history for a session
    DELETE /api/session/{session_id} — clear conversation history for a session
    GET  /health                  — health check
    GET  /docs                    — Swagger UI (auto-generated by FastAPI)
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

from fastapi import FastAPI, HTTPException, Path
from pydantic import BaseModel, Field

from assistant import Assistant
from config import Config

logger = logging.getLogger(__name__)

app = FastAPI(
    title="MaxKonvert Assistant API",
    description=(
        "HTTP API для управления диалогами с ассистентом MaxKonvert. "
        "Все запросы к `/api/chat` требуют `session_id` — это токен сессии/чата. "
        "При повторном использовании того же `session_id` история диалога восстанавливается."
    ),
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

assistant = Assistant()


class ChatRequest(BaseModel):
    message: str = Field(
        ..., min_length=1, description="Текст сообщения пользователя"
    )
    session_id: str = Field(
        ..., min_length=1, description="Обязательный токен сессии (например, токен чата). Используется для сохранения и восстановления контекста диалога."
    )
    user_id: str | None = Field(
        None, description="Опциональный идентификатор пользователя"
    )
    metadata: dict[str, Any] | None = Field(
        None, description="Дополнительные метаданные запроса"
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "session_id": "chat_12345",
                    "message": "Привет, расскажи про условия MaxKonvert",
                    "user_id": "user_67890",
                    "metadata": {"source": "web_widget"},
                },
                {
                    "session_id": "telegram_chat_42",
                    "message": "А сколько стоит WAP?",
                    "user_id": "telegram_user_99",
                    "metadata": {"channel": "telegram_bridge"},
                },
            ]
        }
    }


class ChatResponse(BaseModel):
    answer: str = Field(..., description="Ответ ассистента")
    route: str = Field(..., description="Внутренний маршрут обработки (например, model, fallback)")
    best_score: float = Field(..., description="Оценка релевантности по базе знаний")
    elapsed_ms: int = Field(..., description="Время обработки запроса в миллисекундах")
    model: str = Field(..., description="Используемая модель")
    provider: str = Field(..., description="Используемый провайдер LLM")
    timestamp: str = Field(..., description="UTC timestamp ответа в формате ISO 8601")
    session_id: str = Field(..., description="Токен сессии, переданный в запросе")

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "answer": "Привет! MaxKonvert предлагает монетизацию через MT, WAP, pseudo и premium SMS.",
                    "route": "model",
                    "best_score": 0.78,
                    "elapsed_ms": 1240,
                    "model": "kimi-for-coding",
                    "provider": "kimi",
                    "timestamp": "2026-04-16T10:00:00+00:00",
                    "session_id": "chat_12345",
                }
            ]
        }
    }


class SessionHistoryResponse(BaseModel):
    session_id: str
    turns: list[dict[str, str]] = Field(..., description="Список сообщений в сессии")

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "session_id": "chat_12345",
                    "turns": [
                        {"role": "user", "text": "Привет"},
                        {"role": "assistant", "text": "Привет! Чем могу помочь?"},
                    ],
                }
            ]
        }
    }


class ClearSessionResponse(BaseModel):
    session_id: str
    status: str = Field(..., description="Результат операции")


class HealthResponse(BaseModel):
    status: str
    service: str
    provider: str
    model: str
    started_at_utc: str

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "status": "ok",
                    "service": "maxkonvert-assistant-api",
                    "provider": "kimi",
                    "model": "kimi-for-coding",
                    "started_at_utc": "2026-04-16T10:00:00+00:00",
                }
            ]
        }
    }


@app.on_event("startup")
async def startup():
    errors = Config.validate()
    if errors:
        for err in errors:
            logger.error("Config validation error: %s", err)
        raise RuntimeError("Configuration invalid: " + "; ".join(errors))
    assistant.ensure_index()
    logger.info(
        "API server started; provider=%s model=%s",
        assistant.provider.name,
        assistant.provider.model_id,
    )


@app.get("/health", response_model=HealthResponse, summary="Проверка здоровья сервиса")
async def health() -> dict[str, Any]:
    return {
        "status": "ok",
        "service": "maxkonvert-assistant-api",
        "provider": assistant.provider.name,
        "model": assistant.provider.model_id,
        "started_at_utc": datetime.now(timezone.utc).isoformat(),
    }


@app.post(
    "/api/chat",
    response_model=ChatResponse,
    summary="Отправить сообщение ассистенту",
    description=(
        "Отправляет сообщение пользователя в ассистент. "
        "`session_id` является обязательным токеном сессии. "
        "Если сессия с таким токеном уже существует, восстанавливается история диалога."
    ),
)
async def chat(req: ChatRequest) -> ChatResponse:
    key = req.session_id
    metadata = {"channel": "http_api", **(req.metadata or {})}
    if req.user_id:
        metadata["user_id"] = req.user_id

    try:
        result = await assistant.process_message(
            user_text=req.message.strip(),
            conversation_key=key,
            channel="http_api",
            metadata=metadata,
        )
    except Exception as exc:
        logger.exception("API processing error")
        raise HTTPException(status_code=500, detail=f"Processing error: {exc}")

    return ChatResponse(
        answer=result["answer"],
        route=result["route"],
        best_score=result["best_score"],
        elapsed_ms=result["elapsed_ms"],
        model=assistant.provider.model_id,
        provider=assistant.provider.name,
        timestamp=datetime.now(timezone.utc).isoformat(),
        session_id=key,
    )


@app.get(
    "/api/session/{session_id}",
    response_model=SessionHistoryResponse,
    summary="Получить историю диалога сессии",
    description="Возвращает сохранённую историю сообщений для указанного `session_id`.",
)
async def get_session(
    session_id: str = Path(..., description="Токен сессии", examples=["chat_12345"])
) -> SessionHistoryResponse:
    assistant._load_memory(session_id)
    history = list(assistant.conversation_memory.get(session_id, []))
    return SessionHistoryResponse(session_id=session_id, turns=history)


@app.delete(
    "/api/session/{session_id}",
    response_model=ClearSessionResponse,
    summary="Очистить историю диалога сессии",
    description="Удаляет из памяти и с диска историю сообщений для указанного `session_id`.",
)
async def clear_session(
    session_id: str = Path(..., description="Токен сессии", examples=["chat_12345"])
) -> ClearSessionResponse:
    assistant.clear_memory(session_id)
    return ClearSessionResponse(session_id=session_id, status="cleared")
